app:
  port: "8080"
  env: "development"

database:
  host: "db"
  port: "5432"
  user: "postgres"
  password: "postgres"
  name: "booking"

redis:
  host: "redis"
  port: "6379"

kafka:
  broker: "kafka:9092"
